name: Build and Release MiceWine RootFS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Environment Preparation"
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip cmake wget git p7zip build-essential pkg-config xmlto fop xsltproc llvm autoconf libxml-parser-perl bison flex
        pip3 install mako meson ninja
        sudo ln -sf ~/.local/bin/meson /usr/bin/meson
        
    - name: "Start Building (aarch64)"
      run: |
        ./build-all.sh aarch64
        mv logs /data/data/com.micewine.emu/files/usr

    - name: "Create RootFS File (aarch64)"
      run: |
        ./create-rootfs.sh aarch64

    - name: "Clean AArch64 RootFS"
      run: |
        sudo rm -rf /data/data/ workdir
    
    - name: "Start Building (x86_64)"
      run: |
        ./build-all.sh x86_64
        mv logs /data/data/com.micewine.emu/files/usr
        
    - name: "Create RootFS File (x86_64)"
      run: |
        ./create-rootfs.sh x86_64
          
    - name: "Create Release"
      uses: softprops/action-gh-release@v2
      with:
        name: "MiceWine RootFS ${{ github.sha }}"
        tag_name: rootfs
        files: |
            /home/runner/MiceWine-RootFS-aarch64.zip
            /home/runner/MiceWine-RootFS-x86_64.zip
